### ISSUE TITLE
PR checks fail because of automerge action

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ui#136]
Pipelines fail, if the dependency update is greater than patch level. Instead of failing overall checks, this step shall be made optional. I think that continue-on-error might not be sufficient on job level, but must be added to step level too.
https://github.com/sovity/edc-ui/blob/deaeac14618c3de4f6bda160f44075a2db2c0bbf/.github/workflows/automerge.yml#L9

**Comment by omarsilva1** [comment]
I created a PR but I'm not sure this will completely fix it. 

The problem is that continue-on-error isn't displayed in the UI properly, since it looks red like it is a normal PR failure, even though failure in this case is allowed. (See https://github.com/community/community/discussions/15452).

Unfortunately github doesn't support something like allow-failure, so seems to not be possible to add soemthing like continue-on-error on step level. (See https://github.com/actions/runner/issues/2347).
