### ISSUE TITLE
Add API-Access Information to the Dashboard

### ISSUE THREAD

**Issue by efiege** [sovity/edc-ui#440]
# Feature Request

## Description

Simplify using the API, by displaying corresponding information in the dashboard page.

**Comment by richardtreier** [comment]
- This requires an additional UI Config attribute that will have to be set by the deployer.
- Using the Management API URL the UI is using is not correct.
- This is due to the fact that the Management API needs to be secured with a deployment-specific auth solution, and most people use an auth proxy, the URL or way of access can vary between the UI and API Clients.

**Comment by SebastianOpriel** [comment]
Already implemented 
![image](https://github.com/user-attachments/assets/918a4096-23f6-4389-8f75-b0cbf699953a)
