### ISSUE TITLE
Find reasons for the field "Content Type" to exist, and if there are none, remove it for now.

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#88]
## Feature
The "Content Type" Asset Property has been around since the official EDC DataDashboard repository.

Our Assets, however, are not guaranteed to be HTTP resources or files. They could be databases or access to message queues.

Thus providing an asset property with a mime type seems wrong, at least for now.

## Proposed Solution
- [ ] Find out if any EDC Backend code is actually dependant on this asset prop.
- [ ] If not, let's remove the asset property from our UI (and thus our future assets):
  - [ ] Asset Card
  - [ ] Asset Detail Dialog
  - [ ] Asset Create Dialog with all its units (remove it from the form, search the repository for the names of the field to make sure you found all places were found)

**Comment by omarsilva1** [comment]
The content type field is defiend in the Asset class in the core EDC, it's one of the possible parameters from an Asset (such as name, version, etc).  

https://github.com/eclipse-edc/Connector/blob/67a70aca6b263f6737bd2ffc1327562658029232/spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/asset/Asset.java#L40
 
@efiege mentionend that this is one of the few fields that can be searched for in the database. 

The propety `PROPERTY_CONTENT_TYPE` isn't actually used in EDC Core, but since it's a valid field I think it's best not to remove it from the EDC UI. mi

**Comment by richardtreier** [comment]
We'll keep the field for now, because:
- It is supported well (?) by DCAT, and we'll continue supporting it in EDC 0, see #459 
- With file upload underway we will support additional "file properties" for file-type assets
- The MDS and Mobilithek actually use a lot of file-type assets rather than data sources such as APIs and Streams
